spring:
  datasource:
    url: jdbc:h2:mem:prospectdb
    driverClassName: org.h2.Driver
    username: sa
    password: example
  h2:
    console:
      enabled: true
      console:
        path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE